services:
  data-service:
    build:
      context: ./data_service
      dockerfile: Dockerfile
    container_name: data-service
    ports:
      - "5000:5000"
    env_file: .env
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - data-service
    restart: always
