version: "3.8"
services:
  data-service:
    build: ./data_service
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    environment:
      - DATA_SERVICE_HOST=data-service
      - DATA_SERVICE_PORT=5000
    ports:
      - "8000:8000"
    depends_on:
      - data-service
    restart: unless-stopped